"""initial schema

Revision ID: 05bad99d6631
Revises: 
Create Date: 2026-10-02 17:24:51.267833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bad99d6631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.String(length=5), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('barber_name', sa.String(length=80), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_barber_id'), ['barber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('barbers',
    sa.Column('altegio_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.Column('left', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('altegio_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('client_profiles',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('asof', sa.Date(), nullable=False),
    sa.Column('first_visit', sa.Date(), nullable=True),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('lifetime_spend', sa.Float(), nullable=False),
    sa.Column('usual_barber', sa.Integer(), nullable=True),
    sa.Column('last_barber', sa.Integer(), nullable=True),
    sa.Column('median_gap_days', sa.Float(), nullable=True),
    sa.Column('days_since_last', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('suggested_offer', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('clients',
    sa.Column('altegio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('data_processing_allowed', sa.Boolean(), nullable=True),
    sa.Column('mass_notification_allowed', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('updated_from_altegio_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('altegio_id')
    )
    op.create_table('goal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.String(length=60), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_events_goal_id'), ['goal_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('manual_current', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_scope'), ['scope'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('treatment', sa.JSON(), nullable=False),
    sa.Column('control', sa.JSON(), nullable=False),
    sa.Column('intervention_date', sa.Date(), nullable=True),
    sa.Column('pre_weeks', sa.Integer(), nullable=False),
    sa.Column('post_weeks', sa.Integer(), nullable=False),
    sa.Column('expected', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asof', sa.Date(), nullable=False),
    sa.Column('window_from', sa.Date(), nullable=False),
    sa.Column('window_to', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asof', 'scope', 'metric')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_asof'), ['asof'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_scope'), ['scope'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_date_from'), ['date_from'], unique=False)

    op.create_table('offers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('outreach_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('suggested_offer', sa.String(length=40), nullable=True),
    sa.Column('offer_arm', sa.String(length=40), nullable=True),
    sa.Column('offer_given', sa.String(length=40), nullable=True),
    sa.Column('assigned_to', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contacted_on', sa.Date(), nullable=True),
    sa.Column('returned_on', sa.Date(), nullable=True),
    sa.Column('revenue_recovered', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('closed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_cases_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_cases_status'), ['status'], unique=False)

    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barber_id', 'date', 'start_min')
    )
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_slots_barber_id'), ['barber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_slots_date'), ['date'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('started', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_from', sa.Date(), nullable=True),
    sa.Column('window_to', sa.Date(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('barbers', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_services_appointment_id'), ['appointment_id'], unique=False)

    op.create_table('outreach_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('offer_given', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['outreach_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_events_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_events_case_id'))

    op.drop_table('outreach_events')
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_services_appointment_id'))

    op.drop_table('appointment_services')
    op.drop_table('tips')
    op.drop_table('sync_runs')
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_slots_date'))
        batch_op.drop_index(batch_op.f('ix_schedule_slots_barber_id'))

    op.drop_table('schedule_slots')
    with op.batch_alter_table('outreach_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_cases_status'))
        batch_op.drop_index(batch_op.f('ix_outreach_cases_client_id'))

    op.drop_table('outreach_cases')
    op.drop_table('offers')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_date_from'))

    op.drop_table('notes')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_scope'))
        batch_op.drop_index(batch_op.f('ix_measurements_metric'))
        batch_op.drop_index(batch_op.f('ix_measurements_asof'))

    op.drop_table('measurements')
    op.drop_table('hypotheses')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_scope'))

    op.drop_table('goals')
    with op.batch_alter_table('goal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_events_goal_id'))

    op.drop_table('goal_events')
    op.drop_table('clients')
    op.drop_table('client_profiles')
    op.drop_table('barbers')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_date'))
        batch_op.drop_index(batch_op.f('ix_appointments_client_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_barber_id'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
